# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Hyu\PycharmProjects\OpenCV\uis\mainwindow_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 9, 9, 1, 1)
        self.ratiotestCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ratiotestCheckBox.setObjectName("ratiotestCheckBox")
        self.gridLayout_2.addWidget(self.ratiotestCheckBox, 9, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 7, 5, 1, 1)
        self.serializedBtn = QtWidgets.QPushButton(self.centralwidget)
        self.serializedBtn.setObjectName("serializedBtn")
        self.gridLayout_2.addWidget(self.serializedBtn, 6, 2, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_2.addWidget(self.line_14, 4, 1, 3, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 5, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 4, 4, 3, 1)
        self.evalBtn = QtWidgets.QPushButton(self.centralwidget)
        self.evalBtn.setObjectName("evalBtn")
        self.gridLayout_2.addWidget(self.evalBtn, 9, 11, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 9, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 9, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 11, 1, 1)
        self.skelCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.skelCheckBox.setObjectName("skelCheckBox")
        self.gridLayout_2.addWidget(self.skelCheckBox, 9, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 8, 3, 1, 1)
        self.fileOpenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fileOpenBtn.setObjectName("fileOpenBtn")
        self.gridLayout_2.addWidget(self.fileOpenBtn, 4, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 9, 5, 1, 1)
        self.imgDraw = QtWidgets.QLabel(self.centralwidget)
        self.imgDraw.setObjectName("imgDraw")
        self.gridLayout_2.addWidget(self.imgDraw, 1, 2, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 5, 1, 1)
        self.drawBtn = QtWidgets.QPushButton(self.centralwidget)
        self.drawBtn.setObjectName("drawBtn")
        self.gridLayout_2.addWidget(self.drawBtn, 6, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 9, 10, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 5, 9, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 2, 1, 1)
        self.infofenster = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.infofenster.setFont(font)
        self.infofenster.setText("")
        self.infofenster.setObjectName("infofenster")
        self.gridLayout_2.addWidget(self.infofenster, 1, 7, 1, 4)
        self.directorytextfield = QtWidgets.QLabel(self.centralwidget)
        self.directorytextfield.setObjectName("directorytextfield")
        self.gridLayout_2.addWidget(self.directorytextfield, 8, 0, 1, 3)
        self.directoryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.directoryBtn.setObjectName("directoryBtn")
        self.gridLayout_2.addWidget(self.directoryBtn, 4, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 4, 3, 3, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 5, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 4, 6, 3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monogramm erkennung"))
        self.ratiotestCheckBox.setText(_translate("MainWindow", "Ratio Test"))
        self.serializedBtn.setText(_translate("MainWindow", "Serialisierte Daten"))
        self.evalBtn.setText(_translate("MainWindow", "Auswerten"))
        self.skelCheckBox.setText(_translate("MainWindow", "Skeletonize"))
        self.fileOpenBtn.setText(_translate("MainWindow", "Durchsuchen"))
        self.imgDraw.setText(_translate("MainWindow", "Kein Input gewählt"))
        self.label_2.setText(_translate("MainWindow", "                     2."))
        self.drawBtn.setText(_translate("MainWindow", "Zeichnen"))
        self.label_3.setText(_translate("MainWindow", "                   oder"))
        self.label.setText(_translate("MainWindow", "                     1."))
        self.directorytextfield.setText(_translate("MainWindow", "Kein(e) Verzeichnis/Datei ausgewählt"))
        self.directoryBtn.setText(_translate("MainWindow", "Monogram Verzeichnis"))
        self.label_4.setText(_translate("MainWindow", "                   oder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainwindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

