# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Hyu\PycharmProjects\OpenCV\uis\matcheswindow_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
# =============================================================================
# Created By  : Huy Luong
# Created Date: 07.05.2019
# License: GNU GPL
# =============================================================================
# Imports
from PyQt5 import QtCore, QtGui, QtWidgets
# =============================================================================

#AUTO-GENERATED GUI-File
class Ui_matcheswindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.match5Btn = QtWidgets.QPushButton(self.centralwidget)
        self.match5Btn.setObjectName("match5Btn")
        self.gridLayout.addWidget(self.match5Btn, 9, 7, 1, 1)
        self.match3Btn = QtWidgets.QPushButton(self.centralwidget)
        self.match3Btn.setObjectName("match3Btn")
        self.gridLayout.addWidget(self.match3Btn, 5, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 11, 5, 1, 1)
        self.m1 = QtWidgets.QLabel(self.centralwidget)
        self.m1.setObjectName("m1")
        self.gridLayout.addWidget(self.m1, 1, 5, 2, 1)
        self.match1Name = QtWidgets.QLabel(self.centralwidget)
        self.match1Name.setObjectName("match1Name")
        self.gridLayout.addWidget(self.match1Name, 2, 7, 1, 1)
        self.skel4 = QtWidgets.QLabel(self.centralwidget)
        self.skel4.setText("")
        self.skel4.setObjectName("skel4")
        self.gridLayout.addWidget(self.skel4, 7, 3, 2, 1)
        self.skel1 = QtWidgets.QLabel(self.centralwidget)
        self.skel1.setText("")
        self.skel1.setObjectName("skel1")
        self.gridLayout.addWidget(self.skel1, 1, 3, 2, 1)
        self.match5Name = QtWidgets.QLabel(self.centralwidget)
        self.match5Name.setObjectName("match5Name")
        self.gridLayout.addWidget(self.match5Name, 10, 7, 1, 1)
        self.m4 = QtWidgets.QLabel(self.centralwidget)
        self.m4.setObjectName("m4")
        self.gridLayout.addWidget(self.m4, 7, 5, 2, 1)
        self.m3 = QtWidgets.QLabel(self.centralwidget)
        self.m3.setObjectName("m3")
        self.gridLayout.addWidget(self.m3, 5, 5, 2, 1)
        self.inputIMG = QtWidgets.QLabel(self.centralwidget)
        self.inputIMG.setObjectName("inputIMG")
        self.gridLayout.addWidget(self.inputIMG, 3, 0, 5, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 11, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 11, 3, 1, 1)
        self.skel5 = QtWidgets.QLabel(self.centralwidget)
        self.skel5.setText("")
        self.skel5.setObjectName("skel5")
        self.gridLayout.addWidget(self.skel5, 9, 3, 2, 1)
        self.inputImgName = QtWidgets.QLabel(self.centralwidget)
        self.inputImgName.setObjectName("inputImgName")
        self.gridLayout.addWidget(self.inputImgName, 2, 0, 1, 1)
        self.match4Name = QtWidgets.QLabel(self.centralwidget)
        self.match4Name.setObjectName("match4Name")
        self.gridLayout.addWidget(self.match4Name, 8, 7, 1, 1)
        self.match4Btn = QtWidgets.QPushButton(self.centralwidget)
        self.match4Btn.setObjectName("match4Btn")
        self.gridLayout.addWidget(self.match4Btn, 7, 7, 1, 1)
        self.match2Btn = QtWidgets.QPushButton(self.centralwidget)
        self.match2Btn.setObjectName("match2Btn")
        self.gridLayout.addWidget(self.match2Btn, 3, 7, 1, 1)
        self.m5 = QtWidgets.QLabel(self.centralwidget)
        self.m5.setObjectName("m5")
        self.gridLayout.addWidget(self.m5, 9, 5, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 11, 0, 1, 1)
        self.match2Name = QtWidgets.QLabel(self.centralwidget)
        self.match2Name.setObjectName("match2Name")
        self.gridLayout.addWidget(self.match2Name, 4, 7, 1, 1)
        self.skel_input = QtWidgets.QLabel(self.centralwidget)
        self.skel_input.setText("")
        self.skel_input.setObjectName("skel_input")
        self.gridLayout.addWidget(self.skel_input, 3, 2, 5, 1)
        self.match3Name = QtWidgets.QLabel(self.centralwidget)
        self.match3Name.setObjectName("match3Name")
        self.gridLayout.addWidget(self.match3Name, 6, 7, 1, 1)
        self.m2 = QtWidgets.QLabel(self.centralwidget)
        self.m2.setObjectName("m2")
        self.gridLayout.addWidget(self.m2, 3, 5, 2, 1)
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setObjectName("backBtn")
        self.gridLayout.addWidget(self.backBtn, 11, 7, 1, 1)
        self.match1Btn = QtWidgets.QPushButton(self.centralwidget)
        self.match1Btn.setObjectName("match1Btn")
        self.gridLayout.addWidget(self.match1Btn, 1, 7, 1, 1)
        self.skel3 = QtWidgets.QLabel(self.centralwidget)
        self.skel3.setText("")
        self.skel3.setObjectName("skel3")
        self.gridLayout.addWidget(self.skel3, 5, 3, 2, 1)
        self.skel2 = QtWidgets.QLabel(self.centralwidget)
        self.skel2.setText("")
        self.skel2.setObjectName("skel2")
        self.gridLayout.addWidget(self.skel2, 3, 3, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.modified_label = QtWidgets.QLabel(self.centralwidget)
        self.modified_label.setText("")
        self.modified_label.setObjectName("modified_label")
        self.gridLayout.addWidget(self.modified_label, 0, 3, 1, 1)
        self.original_label = QtWidgets.QLabel(self.centralwidget)
        self.original_label.setObjectName("original_label")
        self.gridLayout.addWidget(self.original_label, 0, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.match5Btn.setText(_translate("MainWindow", "show Match 5"))
        self.match3Btn.setText(_translate("MainWindow", "show Match 3"))
        self.m1.setText(_translate("MainWindow", "TextLabel"))
        self.match1Name.setText(_translate("MainWindow", "TextLabel"))
        self.match5Name.setText(_translate("MainWindow", "TextLabel"))
        self.m4.setText(_translate("MainWindow", "TextLabel"))
        self.m3.setText(_translate("MainWindow", "TextLabel"))
        self.inputIMG.setText(_translate("MainWindow", "TextLabel"))
        self.inputImgName.setText(_translate("MainWindow", "TextLabel"))
        self.match4Name.setText(_translate("MainWindow", "TextLabel"))
        self.match4Btn.setText(_translate("MainWindow", "show Match 4"))
        self.match2Btn.setText(_translate("MainWindow", "show Match 2"))
        self.m5.setText(_translate("MainWindow", "TextLabel"))
        self.match2Name.setText(_translate("MainWindow", "TextLabel"))
        self.match3Name.setText(_translate("MainWindow", "TextLabel"))
        self.m2.setText(_translate("MainWindow", "TextLabel"))
        self.backBtn.setText(_translate("MainWindow", "Back"))
        self.match1Btn.setText(_translate("MainWindow", "show Match 1"))
        self.original_label.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_matcheswindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

